### PR TITLE
Fix examples syntax

### PR DESCRIPTION
**Pull request by artonge**
Add missing space in most of the examples

### CODE REVIEW

**Comment by artonge** [comment]
And FYI, I am using you plugin here: https://docs.flap.cloud/#/create_new_service

Thanks a lot, it make the whole thing more readable :).

**Comment by VagnerDomingues** [comment]
Thanks for opening the PR i'm a bit off of here and couldn't see it before, i'm happy to know that it could be of help, and btw can i use the link of flaps docs on the Demo page?

**Comment by artonge** [comment]
Hey ! thanks for finally taking the time to merge this PR. I hope it will help others !

Yes, you can use the URL :).

**Comment by VagnerDomingues** [comment]
i merged and didn't tested before.. looks like there's a limitation for sequential panels where the space between tag and text matches the Regex before it should.. but it works perfectly for single example panels. I don't have time to fix it today, i'll rollback changes and get back to it later, i might have to do a rework on the regex itself.

image
image

**Comment by VagnerDomingues** [comment]
I managed to made it work properly inside the documentation, the thing was that the Regex was matching the code samples and building new panels... thought it would be harder and that i would have to release a new version on NPM, but it was ok...  i think this repo deserves a little more attention... i'l try harder. and thanks!

cheers from Brazil!

**Pull request merged**
